spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: 123456 # 数据库连接密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#以下用于测试cloudBus
info:
  app.name: microcloud-config-client-dev
  company.name: bzng