spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: microconfig-test-dev
---
spring:
 profiles: default
 application:
      name: microconfig-test-default

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka